# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

conda:
    environment: prot_ml_a.yml

build:
   image: latest

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# This part is necessary otherwise the project is not built
python:
   version: 3.8
   install:
      - method: pip
        path: .
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
