# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

conda:
    environment: prot_ml.yml.yml

build:
   image: latest

# This part is necessary otherwise the project is not built
python:
   version: 3.9.12
   install:
      - method: pip
        path: .
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
