site_name: Protein_ML Documentation
site_description: modules for protein phenotype prediction

# Repository
repo_name: Protein_ML
repo_url: https://github.com/AndreaGraf/Protein_ML  

theme:
  name: material
  palette:
    primary: blue
    accent: blue
 

plugins:
  - mkdocstrings
 
nav:
  - Home: index.md
  - modules:
    - protml:
      - apps:
        - train: modules/protml/apps/train.md
      - dataloaders:
        - ddg_data: modules/protml/dataloaders/ddg_data.md
        - utils: modules/protml/dataloaders/utils.md
      - models:
        - baseline_supervised: modules/protml/models/baseline_supervised.md
        - baseline_vae: modules/protml/models/baseline_vae.md
        - components:
          - downstream_models: modules/protml/models/components/downstream_models.md
          - loss_functions: modules/protml/models/components/loss_functions.md
        - decoders:
          - variational_decoder: modules/protml/models/decoders/variational_decoder.md
        - dz_supervised: modules/protml/models/dz_supervised.md
        - encoders:
          - variational_encoder: modules/protml/models/encoders/variational_encoder.md
        - util: modules/protml/models/util.md
      - utils:
        - lightning_utils: modules/protml/utils/lightning_utils.md
        - output_utils: modules/protml/utils/output_utils.md
