_target_: protml.models.decoders.MLPDecoder
model_params:
  hidden_layer_sizes: [50, 100, 100]
  z_dim: ${z_dim}
  initial_non_linearities: "relu"
  final_nonlinearity: "relu"
  dropout_prob: 0.1
  include_temperature_scaler: true
  mu_bias_init: 0.1
  logvar_init: -10.0
  clip_log_var: true