_target_: automl.dataloaders.EmbeddingsDataModule
datafiles:
  embeddings: ${embeddings}
  train: ${train_data}
  val: ${val_data}
  test: ${test_data}
params:
  batch_size: 128
  num_workers: 4
  sequence_length: ${seq_len}
  alphabet_size: 1024